baseURL = "https://example.org"

disableKinds = ["page", "section", "taxonomy", "term"]

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.128.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source       = "hugo_stats.json"
    target       = "assets/notwatching/hugo_stats.json"
    disableWatch = true
[build.buildStats]
  enable = true
[[build.cachebusters]]
  source = "assets/notwatching/hugo_stats\\.json"
  target = "styles\\.css"
[[build.cachebusters]]
  source = "(postcss|tailwind)\\.config\\.js"
  target = "css"
